# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJ28ijq3zUpDPu5U7e2Gsk7IzK79jEje
"""

!pip install flask
!pip install flask-ngrok

from flask import *
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
@app.route('/index')
def home():
  return 'Hello World'

run_with_ngrok(app)
app.run()

* Serving Flask app "__main__" (lazy loading)
 * Environment: production [31m   WARNING: This is a development      server. Do not use it in a production deployment.[0m [2m   Use a production WSGI server instead.[0m
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Running on http://57b01f4a6baf.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040

!pip install fastapi nest-asyncio pyngrok uvicorn

from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn

app = FastAPI()

@app.get('/index')
async def home():
  return "Hello World"

ngrok_tunnel = ngrok.connect(8000)
print('Public URL:', ngrok_tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port=8000)

Public URL: http://af9a6a5b8bdb.ngrok.io


INFO:     Started server process [63]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)