# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1naFo4ZBuarYeR9pvE473zl9-4t5CdUKj
"""

!pip install flask_ngrok

import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import request, jsonify, Flask
import random as rk

app = Flask(__name__)
run_with_ngrok(app)

d = {
    "num": 1,
    "name": "Mahesh",
    "idade": 25,
    "city": "Bangalore",
    "country": "India"
    }, {
    "num": 2,
    "name": "Alex",
    "idade": 26,
    "city": "London",
    "country": "UK"
    }, {
    "num": 3,
    "name": "David",
    "idade": 27,
    "city": "San Francisco",
    "country": "USA"
    }, {
    "num": 4,
    "name": "John",
    "idade": 28,
    "city": "Toronto",
    "country": "Canada"
    }, {
    "num": 5,
    "name": "Chris",
    "idade": 29,
    "city": "Paris",
    "country": "France"
    }

@app.route("/")
def home():
  '''
  The entire line below must be written in a single line.
  '''
  return "<marquee><h3> TO CHECK IN PUT ADD '/input' TO THE URL AND TO CHECK PUT ADD '/output' TO THE URL.<h3><marquee>"

@app.route()
def input():
  return jsonify(d)

@app.route('/output', methods= ['GET', 'POST'])

def predJson():
  pred = r.choice(["positive", "negative"])
  nd = d
  nd ["prediction"] = pred
  return jsonify(nd)

  app.run()